env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns: 
  - webpack.config.js
  - src/libs/**
  - dist/**
rules: {}
